version: 2.1

vars:
  bazel_cache_key: &bazel_cache_key bazel-{{ .Branch }}-1551968594

executors:
  machine:
    machine: true

commands:
  git_tree_must_be_clean:
    description: Error when git tree is not clean
    steps:
      - run:
          name: Test if git tree is clean
          command: |
            git diff
            git status
            test -z "$(git status --porcelain)"

jobs:
  build:
    executor: machine
    steps:
      - checkout
      - restore_cache:
          key: *bazel_cache_key
      - run:
          name: Install bazel
          command: |
            curl -L -o ~/bazel-installer.sh https://github.com/bazelbuild/bazel/releases/download/0.23.1/bazel-0.23.1-installer-linux-x86_64.sh
            chmod +x ~/bazel-installer.sh
            ~/bazel-installer.sh --user
      - run:
          name: Generate BUILD.bazel files
          command: bazel run //:gazelle
      - run:
          name: Format BUILD.bazel files
          command: bazel run //:buildifier
      - git_tree_must_be_clean
      - run:
          name: Build all
          command: bazel build //...
      - run:
          name: Test all
          command: bazel test //...
      - save_cache:
          key: *bazel_cache_key
          paths:
            - ~/.cache/bazel

workflows:
  version: 2

  default:
    jobs:
      - build
