version: 2.1

vars:
  bazel_cache_key: &bazel_cache_key bazel-{{ .Branch }}-1551968494

executors:
  bazel:
    docker:
      - image: gcr.io/cloud-builders/bazel

commands:
  git_tree_must_be_clean:
    description: Error when git tree is not clean
    steps:
      - run:
          name: Test if git tree is clean
          command: |
            git diff
            git status
            test -z "$(git status --porcelain)"

jobs:
  build:
    executor: bazel
    steps:
      - checkout
      - restore_cache:
          key: *bazel_cache_key
      - run:
          name: Format BUILD.bazel files
          command: bazel build //:gazelle
      - save_cache:
          key: *bazel_cache_key
          paths:
            - /workspace/.bazel
      - git_tree_must_be_clean

workflows:
  version: 2

  default:
    jobs:
      - build
